<?
/*
        Copyright (C) 2000-2001 Liquid Bytes (R), Germany. All rights reserved.
        http://www.liquidbytes.net/
 
        This file is part of the liquidbytes.net Adaptive Website Framework (AWF)
        The author is Michael Mayer (michael@liquidbytes.net)
        Last update: 30.04.2001
*/
?>

<table width="100%" cellpadding="0" cellspacing="0 border="0" bgcolor="#000000"><tr><td>
<center><span class="lbfooter">&copy; 2000-2001 Liquid Bytes - 'Liquid Bytes' is a registered trademark of Liquid Bytes e.K.</span></center>
</td>
</tr>
</table>
