<?php
/*
        Copyright (C) 2000-2001 Liquid Bytes (R), Germany. All rights reserved.
        http://www.liquidbytes.net/
 
        This file is part of the liquidbytes.net Adaptive Website Framework (AWF)
        The author is Michael Mayer (michael@liquidbytes.net)
        Last update: 24.08.2001
*/

?>

<center><p>
<img src="img/erdbeere4.gif" border="0"><br>
&copy; 2001 Strawberry Corp.
</p>
</center>


