<center>
<img src="img/error.gif" border="0" />
<font face="arial, helvetica, sans serif, verdana" size="3">
<p>
<b>Don't panic!</b>
</p>
<p>
This page appears, because the connection to a required <?php echo(DBMS.' '); ?>database server can't be 
established. In most cases, the reason is incorrect account information. Please attempt your request again 
(if you are repeatedly unsuccessful you should notify the site administrator).
</p>
